name: Welcome New Contributors

on:
  pull_request:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Thanks for opening your first issue!  
            We appreciate your contribution and look forward to collaborating with you.
          pr-message: |
            🎉 Thank you for your first pull request!  
            We value your input and will review it as soon as possible.
